import type { Translations } from "./types";

export const en: Translations = {
  brand: "The Field",
  markGlyph: "F",
  brandTag: "Padel · Assiut",
  langSwitch: "عربي",
  themeSwitchDark: "Light",
  themeSwitchLight: "Dark",
  signIn: "Sign in",
  signOut: "Sign out",
  joinNow: "Join now",
  nav: { home: "Home", courts: "Courts", locations: "Locations", booking: "Booking" },
  hero: {
    eyebrow: "Padel courts — Assiut, Egypt",
    title: "Book the court.\nPlay the point.",
    sub: "THE FIELD is a padel-only booking platform. Pick a court, pick an hour, and the slot is yours.",
    tag: "Padel courts — Assiut",
    cta1: "Book a court",
    cta2: "Explore courts",
    f1: "3 courts in Assiut",
    f2: "90-minute sessions",
    f3: "Open 08:00 — 01:00",
    scroll: "Scroll",
  },
  courts: {
    eyebrow: "The courts",
    title: "Three courts, one standard",
    note: "Every court is glass-walled, floodlit and maintained daily. Prices are per hour, before tax.",
    perHour: "per hour",
    book: "Book this court",
    images: "images",
  },
  loc: { eyebrow: "Locations", title: "Assiut first. Egypt next." },
  min: {
    l1: "Glass",
    h1: "Four glass walls, floodlit until one in the morning.",
    p1: "Panoramic back walls and black metal framing, so every point stays in view from outside the court.",
    s1v: "4",
    s1k: "Glass walls",
    s2v: "01:00",
    s2k: "Floodlights until",
    l2: "Surface",
    h2: "Resurfaced every season. Swept before every session.",
    p2: "A consistent bounce on every court, checked by our staff before each booking starts.",
    s3v: "1x",
    s3k: "Resurfaced yearly",
    s4v: "90",
    s4k: "Minutes per session",
  },
  book: {
    eyebrow: "Booking",
    title: "Reserve a slot",
    s1: "Location",
    s2: "Court",
    s3: "Date",
    s4: "Time",
    duration: "90 min",
    legendFree: "Available",
    legendTaken: "Booked or held",
    sumCourt: "Court",
    sumWhen: "Date & time",
    sumTotal: "Total",
    cta: "Book now",
    foot: "Availability is confirmed on the server when you book. Your slot is held for 10 minutes while you pay.",
  },
  auth: {
    eyebrow: "Account",
    title: "Sign in to continue",
    sub: "A booking needs an account so we can send your confirmation.",
    email: "Email",
    password: "Password",
    cta: "Sign in and continue",
    back: "Back to booking",
  },
  co: {
    title: "Checkout",
    status: "Booking status",
    total: "Total due",
    hold: "Slot held for",
    back: "Back to landing",
    payTitle: "Payment instructions",
    payNote: "Transfer the total with your chosen method, then upload the receipt below. Admin confirms within a few hours.",
    upTitle: "Payment receipt",
    upHint: "JPG, PNG or PDF — max 5 MB",
    submit: "Submit payment",
    whatsapp: "Sends your booking details to our WhatsApp",
    doneTitle: "Payment submitted",
    doneBody: "Your receipt is with our team. The booking is confirmed once payment is approved.",
    doneRef: "Reference",
    doneNext: "You will get an email and a WhatsApp message on approval.",
    rCourt: "Court",
    rLoc: "Location",
    rDate: "Date",
    rTime: "Time",
    rDur: "Duration",
    rRef: "Reference",
    pMethod: "Method",
    pSendTo: "Send to",
    pName: "Account name",
  },
  footer: {
    blurb: "Padel courts and court booking in Assiut, Egypt.",
    visit: "Visit",
    addr1: "Corniche El Nil",
    addr2: "Assiut, Egypt",
    contact: "Contact",
    phone: "+20 100 000 0000",
    email: "play@thefield.eg",
    hours: "Hours",
    hoursVal: "Daily 08:00 — 01:00",
    rights: "© 2026 THE FIELD",
  },
  pre: { eyebrow: "Assiut, Egypt", line: "Padel.\nNothing else.", loading: "Preparing the court" },
  empty: "—",
  pickFirst: "Select a slot",
  receiptNone: "Attach receipt file",
  receiptSet: "receipt-instapay.jpg attached",
};
